config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    resources :users, only: [:index, :edit, :update]
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :users
  devise_for :admins

  get 'inicio', to: 'site/welcome#index'

  root to: "site/welcome#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/users_controller.rb
class AdminsBackoffice::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :cpf, :birth_date, :phone_number, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :cpf, :birth_date, :phone_number, :email, :password, :current_password)}
         end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/users_helper.rb
module AdminsBackoffice::UsersHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/users/edit.html.erb
<h2>Edição de usuário</h2>
<%= @user.inspect %>
<%= image_tag("teste.jpg") %>

app/views/admins_backoffice/users/index.html.erb
<h2>Lista usuários</h2>
<table>
    <thead>
        <th>ID</th>
        <th></th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Email</th>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td>
                <%= link_to 'e ', edit_admins_backoffice_user_path(user.id), title:"Editar" %>
            </td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/admins_backoffice/welcome/index.html.erb
<ul>
    <li>
        <%= link_to "Listar usuários", admins_backoffice_users_path  %>
    </li>
</ul>

app/views/layouts/_menu.html.erb
<ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Users Backoffice", users_backoffice_welcome_index_path %></li>
    <li><%= link_to "Admin Backoffice", admins_backoffice_welcome_index_path %></li>
</ul>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Participa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/menu" %>
    <% if admin_signed_in? %>
    <% #current_admin.inspect %>
    <%= link_to "Fazer logoff do admin", destroy_admin_session_path, method: :delete %>
    <% end %>
    <h1>Painel administrativo</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Participa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Layout application
    <%= render "/layouts/menu" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Participa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Layout Site
    <%= render "/layouts/menu" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Participa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Layout User
    <%= render "/layouts/menu" %>
    <% if user_signed_in? %>
    <%= current_user.inspect %>
    <br>
    <%= link_to "Editar perfil", edit_user_registration_path %>
    <br>
    <%= link_to "Fazer logoff", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>